update drush and drupal console version (composer)
wunderkraut/wundertools-image-fuzzy-developershell pull request #63
Opened 2017-07-21 06:54 UTC by james-nesbitt

This patch updates the composer included versions for drush and drupal console.  It also includes the php-tokenizer extension which is now a required piece of the composer includes needed.

>>> nikic/php-parser v3.0.6 requires ext-tokenizer * -> the requested PHP extension tokenizer is missing from your system.

whic occurs when we do the global composer update.

2017-07-21 12:43 UTC, james-nesbitt commented on app/.composer/composer.json
> +        "drush/drush": "8.1.12",
should I push Drush to 9.0.0-betaX ?

2017-07-21 13:01 UTC, james-nesbitt commented on app/.composer/composer.json
> +        "drush/drush": "8.1.12",
no Drush 9, as it doesn't work with Drupal 7

2017-07-21 13:04 UTC, james-nesbitt commented
this was rebased to get travis, and to remove the duplicate tokenizer addition.

2017-07-21 13:13 UTC, aleksijohansson requested changes
I think the composer.json is not in use? These versions should be updated in the Dockerfile? At least this is still open https://github.com/wunderkraut/image-fuzzy-alpine-devshell/issues/35.

2017-07-24 07:07 UTC, james-nesbitt commented
```
### Install various composer packages globally, from app/.composer/composer.json
# This includes:
#   - drush
#   - drupal console
RUN mkdir /app/.composer
ADD app/.composer/composer.json /app/.composer/composer.json
RUN composer global update
```

Ithink that the composer update is being used.

2017-07-24 07:07 UTC, james-nesbitt commented
btw, travis fixes are incoming in #70

2017-07-24 08:58 UTC, aleksijohansson commented
@james-nesbitt I see, sorry. I was behind on the latest updates. Didn't realise composer already works for some of the packages. Checks pass so let's merge this.

2017-07-24 08:58 UTC, aleksijohansson approved these changes

2017-07-24 08:58 UTC, merged